# ksadk/server/app.py
"""Default runtime app facade and backwards-compatible server exports."""

from __future__ import annotations

import os
from collections.abc import AsyncIterator
from pathlib import Path
from typing import Any

from fastapi import FastAPI
from fastapi.responses import StreamingResponse

import ksadk.conversations as conversation
from ksadk.server.composition import configure_runtime_app
from ksadk.server.factory import (
    RuntimeAppConfig,
    RuntimeAppState,
    create_runtime_app,
    get_state,
    set_fallback_state,
    shutdown_runtime_resources,
)
from ksadk.server.routes import dependencies as route_dependencies
from ksadk.server.routes.checkpoint_resolution import (
    _find_session_checkpoint,
    _resolve_checkpoint_resume_input_from_session,
)
from ksadk.server.routes.common import (
    _CUSTOM_API_PROXY_ENV_KEYS,
    _HOP_BY_HOP_HEADERS,
    _MAX_INLINE_BASE64_CHARS,
    _MAX_INLINE_TEXT_CHARS,
    _MAX_REFERENCE_TEXT_BYTES,
    _NATIVE_TUI_FRAMEWORKS,
    _RESERVED_UI_PATHS,
    _TEXT_FILE_EXTENSIONS,
    _TEXT_MIME_PREFIXES,
    _TEXT_MIME_TYPES,
    _UPLOAD_URI_SCHEME,
    STATIC_DIR,
    _action_response,
    _attachment_from_part,
    _attachment_prompt_text,
    _build_bootstrap_model_payload,
    _build_native_terminal_capability,
    _current_framework,
    _custom_api_proxy_base_url,
    _decode_inline_data,
    _default_custom_ui_bundle_dir,
    _ensure_runner_loaded,
    _ensure_session,
    _extract_inline_attachment_text,
    _extract_pdf_text,
    _extract_user_input_from_parts,
    _hydrate_session,
    _is_custom_ui_static_asset_path,
    _is_textual_mime,
    _looks_like_textual_attachment,
    _normalize_request_ui_path,
    _prepare_runner_for_model,
    _proxy_headers,
    _read_attachment_bytes,
    _register_integrated_routers,
    _request_id,
    _resolve_active_runner,
    _resolve_agent_ui_spec,
    _resolve_attachment_storage_path,
    _resolve_current_model,
    _resolve_ui_static_response,
    _resolve_uploads_dir,
    _response_headers,
    _runner_project_dir,
    _sanitize_session_state_for_action,
    _ui_state_with_env_fallback,
    _workspace_root_dir,
    _workspace_runtime_request,
    custom_api_proxy,
    health_check,
    list_apps,
    set_runner,
)
from ksadk.server.routes.control import (
    get_checkpoint_resume_preview_action,
    resume_run_action,
    subscribe_run_events_action,
)
from ksadk.server.routes.misc import (
    _feedback_payload_from_state,
    _feedback_state_key,
    _find_feedback_assistant_event,
    create_session,
    delete_response_feedback_action,
    delete_session,
    get_agent_builder,
    get_event_graph,
    get_event_trace,
    get_response_feedback_action,
    get_session,
    get_session_trace,
    get_traces,
    list_agent_models_action,
    list_eval_results,
    list_eval_sets,
    list_sessions,
    save_agent_builder,
    save_session_to_memory,
    serve_agent_ui_static,
    upsert_response_feedback_action,
)
from ksadk.server.routes.models import (
    _EVENT_SCAN_PAGE_SIZE,
    _MAX_PREVIEW_TOOL_RECEIPTS,
    _RUN_ACTIVE_STATUSES,
    _RUN_TERMINAL_STATUSES,
    CancelRunActionRequest,
    CreateSessionActionRequest,
    GetCheckpointResumePreviewActionRequest,
    ListSessionCheckpointsActionRequest,
    ListSessionEventsActionRequest,
    ListSessionMessagesActionRequest,
    ListSessionsActionRequest,
    ListToolReceiptsActionRequest,
    ResponseFeedbackRefActionRequest,
    ResponsesRequest,
    ResumeRunActionRequest,
    RunAgentActionRequest,
    SessionIdRequest,
    UiBootstrapRequest,
    UpsertResponseFeedbackActionRequest,
    WorkspaceDeleteActionRequest,
    WorkspaceListActionRequest,
    _clean_optional_string,
    _event_run_id,
    _event_text,
    _latest_session_run_metadata,
    _latest_session_run_status,
    _metadata_invocation_id,
    _parse_iso_datetime,
    _resolve_responses_conversation_id,
    _resolve_responses_session_and_user,
    _run_agent_response_metadata,
    _run_status_payload_status,
    _runtime_agent_id,
    _session_topic_from_events,
    _session_user_prompt_from_event,
    _split_custom_metadata,
    _truncate_session_text,
)
from ksadk.server.routes.openai_compat import (
    ChatCompletionRequest,
    chat_completions,
    list_openai_models,
    responses,
)
from ksadk.server.routes.projection import (
    _SIDE_EFFECT_TOOL_NAMES,
    _agent_contains_invocation,
    _apply_adk_only_latest_resumable,
    _apply_checkpoint_resume_audit,
    _apply_latest_checkpoint_policy,
    _build_checkpoint_resume_preview,
    _check_adk_latest_resumable,
    _checkpoint_event_to_action_payload,
    _checkpoint_resume_disabled_detail,
    _event_invocation_id,
    _event_to_action_payload,
    _extend_invocation_after_window,
    _extend_invocation_before_window,
    _iter_agent_event_pages,
    _iter_scoped_event_pages,
    _iter_session_event_pages,
    _iter_with_idle_heartbeat,
    _latest_invocation_status,
    _oldest_unconsumed_session_events,
    _record_resume_audit,
    _require_action_session,
    _resume_audit_by_checkpoint,
    _session_contains_invocation,
    _session_to_action_payload,
    _tool_receipt_event_to_action_payload,
)
from ksadk.server.routes.routers import (
    GROUP_ROUTERS,
    builder_router,
    control_router,
    debug_router,
    feedback_router,
    health_meta_router,
    models_router,
    openai_compat_router,
    run_router,
    sessions_adk_compat_router,
    sessions_router,
    tools_router,
    ui_bootstrap_router,
    workspace_router,
)
from ksadk.server.routes.run import cancel_agent_changes, run_agent_action, run_sse
from ksadk.server.routes.sessions import (
    _count_resumable_checkpoints,
    _list_checkpoints_payload,
    create_session_action,
    delete_session_action,
    get_agent_ui_bootstrap,
    get_session_action,
    list_session_checkpoints_action,
    list_session_events_action,
    list_session_messages_action,
    list_sessions_action,
    list_tool_receipts_action,
)
from ksadk.server.routes.streaming import (
    _cancel_detached_streams_for_session,
    _clear_detached_resume_key,
    _detached_resume_key_from_input,
    _DetachedSSEStream,
    _reject_if_detached_resume_active,
)
from ksadk.server.routes.workspace import (
    ListAgentModelsRequest,
    _build_models_payload,
    _normalize_model_catalog_items,
    attachment_content_action,
    cancel_run_action,
    delete_workspace_file_action,
    export_workspace_zip,
    get_workspace_file_content_action,
    list_workspace_files_action,
    upload_file_action,
    upload_workspace_file_action,
    workspace_file_path_route,
)
from ksadk.sessions import describe_session_backend, resolve_session_service

# These names were historically importable from this module. Keeping an explicit
# registry documents the facade and prevents static tooling from deleting aliases.
_COMPAT_EXPORTS = (
    Path,
    RuntimeAppState,
    describe_session_backend,
    get_state,
    _find_session_checkpoint,
    _resolve_checkpoint_resume_input_from_session,
    STATIC_DIR,
    _CUSTOM_API_PROXY_ENV_KEYS,
    _HOP_BY_HOP_HEADERS,
    _MAX_INLINE_BASE64_CHARS,
    _MAX_INLINE_TEXT_CHARS,
    _MAX_REFERENCE_TEXT_BYTES,
    _NATIVE_TUI_FRAMEWORKS,
    _RESERVED_UI_PATHS,
    _TEXT_FILE_EXTENSIONS,
    _TEXT_MIME_PREFIXES,
    _TEXT_MIME_TYPES,
    _UPLOAD_URI_SCHEME,
    _action_response,
    _attachment_from_part,
    _attachment_prompt_text,
    _build_bootstrap_model_payload,
    _build_native_terminal_capability,
    _current_framework,
    _custom_api_proxy_base_url,
    _decode_inline_data,
    _default_custom_ui_bundle_dir,
    _ensure_runner_loaded,
    _ensure_session,
    _extract_inline_attachment_text,
    _extract_pdf_text,
    _extract_user_input_from_parts,
    _hydrate_session,
    _is_custom_ui_static_asset_path,
    _is_textual_mime,
    _looks_like_textual_attachment,
    _normalize_request_ui_path,
    _prepare_runner_for_model,
    _proxy_headers,
    _read_attachment_bytes,
    _register_integrated_routers,
    _request_id,
    _resolve_active_runner,
    _resolve_agent_ui_spec,
    _resolve_attachment_storage_path,
    _resolve_current_model,
    _resolve_ui_static_response,
    _resolve_uploads_dir,
    _response_headers,
    _runner_project_dir,
    _sanitize_session_state_for_action,
    _ui_state_with_env_fallback,
    _workspace_root_dir,
    _workspace_runtime_request,
    custom_api_proxy,
    health_check,
    list_apps,
    set_runner,
    get_checkpoint_resume_preview_action,
    resume_run_action,
    subscribe_run_events_action,
    _feedback_payload_from_state,
    _feedback_state_key,
    _find_feedback_assistant_event,
    create_session,
    delete_response_feedback_action,
    delete_session,
    get_agent_builder,
    get_event_graph,
    get_event_trace,
    get_response_feedback_action,
    get_session,
    get_session_trace,
    get_traces,
    list_agent_models_action,
    list_eval_results,
    list_eval_sets,
    list_sessions,
    save_agent_builder,
    save_session_to_memory,
    serve_agent_ui_static,
    upsert_response_feedback_action,
    CancelRunActionRequest,
    CreateSessionActionRequest,
    GetCheckpointResumePreviewActionRequest,
    ListSessionCheckpointsActionRequest,
    ListSessionEventsActionRequest,
    ListSessionMessagesActionRequest,
    ListSessionsActionRequest,
    ListToolReceiptsActionRequest,
    ResponseFeedbackRefActionRequest,
    ResponsesRequest,
    ResumeRunActionRequest,
    RunAgentActionRequest,
    SessionIdRequest,
    UiBootstrapRequest,
    UpsertResponseFeedbackActionRequest,
    WorkspaceDeleteActionRequest,
    WorkspaceListActionRequest,
    _EVENT_SCAN_PAGE_SIZE,
    _MAX_PREVIEW_TOOL_RECEIPTS,
    _RUN_ACTIVE_STATUSES,
    _RUN_TERMINAL_STATUSES,
    _clean_optional_string,
    _event_run_id,
    _event_text,
    _latest_session_run_metadata,
    _latest_session_run_status,
    _metadata_invocation_id,
    _parse_iso_datetime,
    _resolve_responses_conversation_id,
    _resolve_responses_session_and_user,
    _run_agent_response_metadata,
    _run_status_payload_status,
    _runtime_agent_id,
    _session_topic_from_events,
    _session_user_prompt_from_event,
    _split_custom_metadata,
    _truncate_session_text,
    ChatCompletionRequest,
    chat_completions,
    list_openai_models,
    responses,
    _agent_contains_invocation,
    _SIDE_EFFECT_TOOL_NAMES,
    _apply_adk_only_latest_resumable,
    _apply_checkpoint_resume_audit,
    _apply_latest_checkpoint_policy,
    _build_checkpoint_resume_preview,
    _check_adk_latest_resumable,
    _checkpoint_event_to_action_payload,
    _checkpoint_resume_disabled_detail,
    _event_invocation_id,
    _event_to_action_payload,
    _extend_invocation_after_window,
    _extend_invocation_before_window,
    _iter_agent_event_pages,
    _iter_scoped_event_pages,
    _iter_session_event_pages,
    _iter_with_idle_heartbeat,
    _latest_invocation_status,
    _oldest_unconsumed_session_events,
    _record_resume_audit,
    _require_action_session,
    _resume_audit_by_checkpoint,
    _session_contains_invocation,
    _session_to_action_payload,
    _tool_receipt_event_to_action_payload,
    builder_router,
    control_router,
    debug_router,
    feedback_router,
    health_meta_router,
    models_router,
    openai_compat_router,
    run_router,
    sessions_adk_compat_router,
    sessions_router,
    tools_router,
    ui_bootstrap_router,
    workspace_router,
    cancel_agent_changes,
    run_agent_action,
    run_sse,
    _count_resumable_checkpoints,
    _list_checkpoints_payload,
    create_session_action,
    delete_session_action,
    get_agent_ui_bootstrap,
    get_session_action,
    list_session_checkpoints_action,
    list_session_events_action,
    list_session_messages_action,
    list_sessions_action,
    list_tool_receipts_action,
    _cancel_detached_streams_for_session,
    _detached_resume_key_from_input,
    _reject_if_detached_resume_active,
    ListAgentModelsRequest,
    _build_models_payload,
    _normalize_model_catalog_items,
    attachment_content_action,
    cancel_run_action,
    delete_workspace_file_action,
    export_workspace_zip,
    get_workspace_file_content_action,
    list_workspace_files_action,
    upload_file_action,
    upload_workspace_file_action,
    workspace_file_path_route,
)


SSE_HEARTBEAT_INTERVAL_SECONDS = max(
    1.0,
    float(os.getenv("AGENTENGINE_SSE_HEARTBEAT_SECONDS", "15")),
)

_GROUP_ROUTERS = GROUP_ROUTERS
_configure_runtime_app = configure_runtime_app
_shutdown_runner_resources = shutdown_runtime_resources


def _detached_streaming_response(
    source: AsyncIterator[str],
    *,
    invocation_id: str | None = None,
    session_id: str | None = None,
    resume_key: tuple[str, str] | None = None,
    run_mode: str = "unknown",
    run_trigger: str = "unknown",
) -> StreamingResponse:
    """Build a detached response through the monkeypatch-compatible facade."""
    detached = _DetachedSSEStream(
        source,
        invocation_id=invocation_id,
        session_id=session_id,
        run_mode=run_mode,
        run_trigger=run_trigger,
    )
    registry = detached._registry
    if invocation_id and resume_key:
        registry.resume_keys_by_invocation[invocation_id] = resume_key
        registry.active_resume_invocation_by_key[resume_key] = invocation_id
        detached._task.add_done_callback(
            lambda _task: _clear_detached_resume_key(registry, invocation_id, resume_key)
        )
    return StreamingResponse(detached.iter_for_client(), media_type="text/event-stream")


route_dependencies.configure(
    route_dependencies.ServerRouteDependencies(
        resolve_session_service=lambda: resolve_session_service(),
        describe_session_backend=lambda: describe_session_backend(),
        resolve_agent_ui_spec=lambda: _resolve_agent_ui_spec(),
        conversation=lambda: conversation,
        detached_streaming_response=lambda *args, **kwargs: _detached_streaming_response(
            *args, **kwargs
        ),
        detached_stream_class=lambda: _DetachedSSEStream,
        heartbeat_interval=lambda: SSE_HEARTBEAT_INTERVAL_SECONDS,
        runtime_app=lambda: app,
    )
)

app: FastAPI = create_runtime_app(
    RuntimeAppConfig(
        # Keep the documented facade injection seam dynamic. New factory users
        # get app-owned services unless they explicitly supply a provider.
        session_service_provider=lambda: resolve_session_service(),
        session_backend_provider=lambda: describe_session_backend(),
    ),
    configure_runtime_app,
)
set_fallback_state(app.state.runtime)
terminal_manager = app.state.runtime.terminal_manager


def __getattr__(name: str) -> Any:
    """Expose the default app's detached stream registry during migration."""
    if name == "_DETACHED_STREAMS_BY_INVOCATION":
        return app.state.runtime.stream_registry.streams_by_invocation
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
