from __future__ import annotations

import httpx

from ksadk.toolsets import describe_agentengine_tools, get_agentengine_tools
from ksadk.toolsets.web import web_fetch, web_search


def test_web_tools_are_registered_in_default_toolset():
    names = {tool.name for tool in get_agentengine_tools()}

    assert "web_fetch" in names
    assert "web_search" in names


def test_web_tool_descriptors_include_web_group():
    specs = {spec["name"]: spec for spec in describe_agentengine_tools(include=["web"])}

    assert specs["web_fetch"]["group"] == "web"
    assert specs["web_search"]["group"] == "web"


def test_web_fetch_blocks_loopback_before_request(monkeypatch):
    def _should_not_request(*_args, **_kwargs):
        raise AssertionError("web_fetch must block loopback URLs before issuing requests")

    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _should_not_request)

    result = web_fetch("http://127.0.0.1:8000/secret")

    assert result["ok"] is False
    assert result["error_type"] == "blocked_by_ssrf_policy"


def test_web_fetch_blocks_private_link_local_and_metadata_addresses(monkeypatch):
    def _should_not_request(*_args, **_kwargs):
        raise AssertionError("web_fetch must block non-public URLs before issuing requests")

    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _should_not_request)

    for url in (
        "http://10.0.0.2/admin",
        "http://192.168.1.2/admin",
        "http://169.254.169.254/latest/meta-data",
    ):
        result = web_fetch(url)
        assert result["ok"] is False
        assert result["error_type"] == "blocked_by_ssrf_policy"


def test_web_fetch_blocks_redirect_to_private_address(monkeypatch):
    calls: list[str] = []

    def _fake_get(self, url, **kwargs):
        calls.append(url)
        return httpx.Response(
            302,
            headers={"location": "http://10.0.0.2/admin"},
            request=httpx.Request("GET", url),
        )

    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _fake_get)

    result = web_fetch("https://example.com/redirect")

    assert result["ok"] is False
    assert result["error_type"] == "blocked_by_ssrf_policy"
    assert calls == ["https://example.com/redirect"]


def test_web_fetch_strips_html_and_budgets_large_content(monkeypatch, tmp_path):
    def _fake_get(self, url, **kwargs):
        return httpx.Response(
            200,
            headers={"content-type": "text/html"},
            text="<html><script>bad()</script><body><h1>Hello</h1><p>"
            + ("world " * 20)
            + "</p></body></html>",
            request=httpx.Request("GET", url),
        )

    monkeypatch.setenv("KSADK_WEB_SSRF_POLICY_JSON", '{"allow_private": true}')
    monkeypatch.setenv("KSADK_TOOL_RESULT_DIR", str(tmp_path))
    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _fake_get)

    result = web_fetch("https://example.com/docs", max_chars=25)

    assert result["ok"] is True
    assert "bad()" not in result["text"]
    assert "Hello" in result["text"]
    assert result["truncated"] is True
    assert result["persisted"]["mime_type"] == "text/plain"


def test_web_search_returns_provider_not_configured_without_provider(monkeypatch):
    monkeypatch.delenv("KSADK_WEB_SEARCH_PROVIDER", raising=False)
    monkeypatch.delenv("OPENCLAW_WEB_SEARCH_PROVIDER", raising=False)

    result = web_search("ksadk sandbox")

    assert result["ok"] is False
    assert result["error_type"] == "provider_not_configured"


def test_web_search_fake_provider_returns_results(monkeypatch):
    monkeypatch.setenv("KSADK_WEB_SEARCH_PROVIDER", "fake")

    result = web_search("ksadk sandbox", max_results=2)

    assert result["ok"] is True
    assert result["provider"] == "fake"
    assert result["results"] == [
        {
            "title": "Fake result for ksadk sandbox",
            "url": "https://example.com/search?q=ksadk+sandbox",
            "snippet": "Fake search result generated by ksadk test provider.",
            "rank": 1,
            "provider": "fake",
        }
    ]


def test_web_search_http_provider_uses_configured_endpoint(monkeypatch):
    captured = {}

    def _fake_get(self, url, **kwargs):
        captured["url"] = url
        captured["params"] = kwargs.get("params")
        captured["headers"] = kwargs.get("headers")
        return httpx.Response(
            200,
            json={
                "results": [
                    {"title": "Doc", "url": "https://example.com/doc", "snippet": "Snippet"}
                ]
            },
            request=httpx.Request("GET", url),
        )

    monkeypatch.setenv("KSADK_WEB_SEARCH_PROVIDER", "http")
    monkeypatch.setenv("KSADK_WEB_SEARCH_BASE_URL", "https://search.example/api")
    monkeypatch.setenv("KSADK_WEB_SEARCH_API_KEY", "secret")
    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _fake_get)

    result = web_search("ksadk tools", max_results=3, recency_days=7)

    assert result["ok"] is True
    assert result["provider"] == "http"
    assert captured["params"] == {"q": "ksadk tools", "max_results": 3, "recency_days": 7}
    assert captured["headers"]["Authorization"] == "Bearer secret"
    assert result["results"][0]["rank"] == 1


def test_web_search_ksyun_provider_posts_to_ai_search_endpoint(monkeypatch):
    captured = {}

    def _fake_post(self, url, **kwargs):
        captured["url"] = url
        captured["headers"] = kwargs.get("headers")
        captured["json"] = kwargs.get("json")
        return httpx.Response(
            200,
            json={
                "webpages": [
                    {
                        "title": "KsADK 文档",
                        "link": "https://example.com/ksadk",
                        "snippet": "KsADK 是金山云 Agent 开发工具包。",
                        "date": "2026年07月01日",
                        "position": 1,
                    }
                ],
                "credits": 3,
                "total": 1,
            },
            request=httpx.Request("POST", url),
        )

    monkeypatch.setenv("KSADK_WEB_SEARCH_PROVIDER", "ksyun")
    monkeypatch.setenv("KSADK_WEB_SEARCH_API_KEY", "ksyun-token")
    monkeypatch.delenv("KSADK_WEB_SEARCH_BASE_URL", raising=False)
    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.post", _fake_post)

    result = web_search("ksadk", max_results=5)

    assert result["ok"] is True
    assert result["provider"] == "ksyun"
    # 金山云 AI搜索用 POST + JSON body，不是 GET + params。
    assert captured["url"] == "https://search.aipro.ksyun.com/v1/aisearch/search"
    assert captured["headers"]["Authorization"] == "Bearer ksyun-token"
    assert captured["json"] == {"q": "ksadk", "scope": "webpage", "size": 5}
    assert len(result["results"]) == 1
    first = result["results"][0]
    assert first["title"] == "KsADK 文档"
    assert first["url"] == "https://example.com/ksadk"
    assert first["snippet"].startswith("KsADK 是金山云")
    assert first["date"] == "2026年07月01日"
    assert first["rank"] == 1
    assert first["provider"] == "ksyun"


def test_web_search_ksyun_provider_reuses_metaso_credentials(monkeypatch):
    # 不设 KSADK_WEB_SEARCH_API_KEY，应回退到 KSADK_MCP_KEY / KSC_AIPRO_API_KEY。
    monkeypatch.setenv("KSADK_WEB_SEARCH_PROVIDER", "ksyun")
    monkeypatch.delenv("KSADK_WEB_SEARCH_API_KEY", raising=False)
    monkeypatch.delenv("OPENCLAW_WEB_SEARCH_API_KEY", raising=False)
    monkeypatch.setenv("KSADK_MCP_KEY", "shared-metaso-token")

    captured = {}

    def _fake_post(self, url, **kwargs):
        captured["headers"] = kwargs.get("headers")
        return httpx.Response(
            200,
            json={"webpages": []},
            request=httpx.Request("POST", url),
        )

    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.post", _fake_post)

    result = web_search("ksadk")

    assert result["ok"] is True
    assert captured["headers"]["Authorization"] == "Bearer shared-metaso-token"


def test_web_search_ksyun_provider_returns_not_configured_without_api_key(monkeypatch):
    monkeypatch.setenv("KSADK_WEB_SEARCH_PROVIDER", "ksyun")
    for key in (
        "KSADK_WEB_SEARCH_API_KEY",
        "OPENCLAW_WEB_SEARCH_API_KEY",
        "KSADK_MCP_KEY",
        "KSC_AIPRO_API_KEY",
        "KSC_AIPRO_APIKEY",
        "AIPRO_API_KEY",
    ):
        monkeypatch.delenv(key, raising=False)

    result = web_search("ksadk")

    assert result["ok"] is False
    assert result["error_type"] == "provider_not_configured"
    assert "api key" in result["error_message"]


def test_web_search_ksyun_provider_respects_custom_scope(monkeypatch):
    captured = {}

    def _fake_post(self, url, **kwargs):
        captured["json"] = kwargs.get("json")
        return httpx.Response(
            200,
            json={"webpages": []},
            request=httpx.Request("POST", url),
        )

    monkeypatch.setenv("KSADK_WEB_SEARCH_PROVIDER", "ksyun")
    monkeypatch.setenv("KSADK_WEB_SEARCH_API_KEY", "token")
    monkeypatch.setenv("KSADK_WEB_SEARCH_SCOPE", "scholar")
    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.post", _fake_post)

    result = web_search("transformer architecture", max_results=10)

    assert result["ok"] is True
    assert captured["json"]["scope"] == "scholar"
    assert captured["json"]["size"] == 10
