from __future__ import annotations

import httpx

from ksadk.toolsets import describe_agentengine_tools, get_agentengine_tools
from ksadk.toolsets.web import web_fetch, web_search


def test_web_tools_are_registered_in_default_toolset():
    names = {tool.name for tool in get_agentengine_tools()}

    assert "web_fetch" in names
    assert "web_search" in names


def test_web_tool_descriptors_include_web_group():
    specs = {spec["name"]: spec for spec in describe_agentengine_tools(include=["web"])}

    assert specs["web_fetch"]["group"] == "web"
    assert specs["web_search"]["group"] == "web"


def test_web_fetch_blocks_loopback_before_request(monkeypatch):
    def _should_not_request(*_args, **_kwargs):
        raise AssertionError("web_fetch must block loopback URLs before issuing requests")

    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _should_not_request)

    result = web_fetch("http://127.0.0.1:8000/secret")

    assert result["ok"] is False
    assert result["error_type"] == "blocked_by_ssrf_policy"


def test_web_fetch_blocks_private_link_local_and_metadata_addresses(monkeypatch):
    def _should_not_request(*_args, **_kwargs):
        raise AssertionError("web_fetch must block non-public URLs before issuing requests")

    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _should_not_request)

    for url in (
        "http://10.0.0.2/admin",
        "http://192.168.1.2/admin",
        "http://169.254.169.254/latest/meta-data",
    ):
        result = web_fetch(url)
        assert result["ok"] is False
        assert result["error_type"] == "blocked_by_ssrf_policy"


def test_web_fetch_blocks_redirect_to_private_address(monkeypatch):
    calls: list[str] = []

    def _fake_get(self, url, **kwargs):
        calls.append(url)
        return httpx.Response(
            302,
            headers={"location": "http://10.0.0.2/admin"},
            request=httpx.Request("GET", url),
        )

    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _fake_get)

    result = web_fetch("https://example.com/redirect")

    assert result["ok"] is False
    assert result["error_type"] == "blocked_by_ssrf_policy"
    assert calls == ["https://example.com/redirect"]


def test_web_fetch_strips_html_and_budgets_large_content(monkeypatch, tmp_path):
    def _fake_get(self, url, **kwargs):
        return httpx.Response(
            200,
            headers={"content-type": "text/html"},
            text="<html><script>bad()</script><body><h1>Hello</h1><p>" + ("world " * 20) + "</p></body></html>",
            request=httpx.Request("GET", url),
        )

    monkeypatch.setenv("KSADK_WEB_SSRF_POLICY_JSON", '{"allow_private": true}')
    monkeypatch.setenv("KSADK_TOOL_RESULT_DIR", str(tmp_path))
    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _fake_get)

    result = web_fetch("https://example.com/docs", max_chars=25)

    assert result["ok"] is True
    assert "bad()" not in result["text"]
    assert "Hello" in result["text"]
    assert result["truncated"] is True
    assert result["persisted"]["mime_type"] == "text/plain"


def test_web_search_returns_provider_not_configured_without_provider(monkeypatch):
    monkeypatch.delenv("KSADK_WEB_SEARCH_PROVIDER", raising=False)
    monkeypatch.delenv("OPENCLAW_WEB_SEARCH_PROVIDER", raising=False)

    result = web_search("ksadk sandbox")

    assert result["ok"] is False
    assert result["error_type"] == "provider_not_configured"


def test_web_search_fake_provider_returns_results(monkeypatch):
    monkeypatch.setenv("KSADK_WEB_SEARCH_PROVIDER", "fake")

    result = web_search("ksadk sandbox", max_results=2)

    assert result["ok"] is True
    assert result["provider"] == "fake"
    assert result["results"] == [
        {
            "title": "Fake result for ksadk sandbox",
            "url": "https://example.com/search?q=ksadk+sandbox",
            "snippet": "Fake search result generated by ksadk test provider.",
            "rank": 1,
            "provider": "fake",
        }
    ]


def test_web_search_http_provider_uses_configured_endpoint(monkeypatch):
    captured = {}

    def _fake_get(self, url, **kwargs):
        captured["url"] = url
        captured["params"] = kwargs.get("params")
        captured["headers"] = kwargs.get("headers")
        return httpx.Response(
            200,
            json={
                "results": [
                    {"title": "Doc", "url": "https://example.com/doc", "snippet": "Snippet"}
                ]
            },
            request=httpx.Request("GET", url),
        )

    monkeypatch.setenv("KSADK_WEB_SEARCH_PROVIDER", "http")
    monkeypatch.setenv("KSADK_WEB_SEARCH_BASE_URL", "https://search.example/api")
    monkeypatch.setenv("KSADK_WEB_SEARCH_API_KEY", "secret")
    monkeypatch.setattr("ksadk.toolsets.web.httpx.Client.get", _fake_get)

    result = web_search("ksadk tools", max_results=3, recency_days=7)

    assert result["ok"] is True
    assert result["provider"] == "http"
    assert captured["params"] == {"q": "ksadk tools", "max_results": 3, "recency_days": 7}
    assert captured["headers"]["Authorization"] == "Bearer secret"
    assert result["results"][0]["rank"] == 1
