"""HTTP request contracts used by the AgentKit Studio control plane."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field, SecretStr, field_validator

from ksadk.conversations.contracts import ConversationInput
from ksadk.evaluation import EvaluationConfig as PublicEvaluationConfig
from ksadk.evaluation import TargetRef
from ksadk.scheduler.contracts import ScheduleSpec
from ksadk.studio.contracts import (
    AgentBindings,
    AgentSpec,
    ContractModel,
    MCPServerRef,
    ModelSpec,
    RuntimeRef,
    ToolContract,
)


class SessionExchangeRequest(ContractModel):
    token: str = Field(min_length=16, max_length=512)


class WorkspaceOpenRequest(ContractModel):
    path: str
    create: bool = False


class CreateAgentRequest(ContractModel):
    id: str = Field(pattern=r"^[a-z][a-z0-9-]{2,62}$")
    name: str = Field(min_length=1, max_length=128)
    description: str = Field(default="", max_length=1024)
    template: str = "blank"
    runtime: RuntimeRef | None = None
    spec: AgentSpec | None = None


class ValidationRequest(ContractModel):
    revision: int = Field(ge=1)
    level: Literal["schema", "build", "release"] = "build"


class BuildRequest(ContractModel):
    revision: int = Field(ge=1)
    run_evaluation: bool = False
    evaluation_suite_refs: list[str] = Field(default_factory=list)


class ImportRootRequest(ContractModel):
    """一键导入根 Framework 项目（方案 §6.1）。"""
    name: str | None = None
    slug: str | None = None


class PromptCompileRequest(ContractModel):
    """PR-S2：Prompt 编译预览请求（方案 §6.2）。只读，不写 Session/Trace。"""
    revision: int = Field(default=1, ge=1)
    request_instructions: str = Field(default="", max_length=32768)
    include_content: bool = False  # local debug 显式请求正文


class ContextPreviewRequest(ContractModel):
    """PR-S2：Context 预览请求（方案 §6.2）。复用真实 Planner，不调模型。"""
    revision: int = Field(default=1, ge=1)
    user_input: str = Field(default="", max_length=1_000_000)
    request_instructions: str = Field(default="", max_length=32768)
    simulated_history: list[MessageInput] = Field(default_factory=list)
    include_content: bool = False


class MessageInput(ContractModel):
    role: str = "user"
    content: str = Field(min_length=1, max_length=1_000_000)


class QuickAuthoringRequest(ContractModel):
    name: str = Field(min_length=1, max_length=128)
    slug: str | None = Field(default=None, min_length=1, max_length=63)
    runtime_type: Literal["codex", "adk", "langgraph", "plugin"]
    template: Literal["blank", "research"] = "blank"
    description: str = Field(default="", max_length=1024)
    spec: AgentSpec | None = None


class AuthoringConversationMessage(ContractModel):
    role: Literal["user", "assistant"]
    content: str = Field(min_length=1, max_length=32768)


class ConversationAuthoringRequest(ContractModel):
    messages: list[AuthoringConversationMessage] = Field(min_length=1, max_length=100)
    # This is the single profile used to generate the Draft Patch.  It is not
    # implicitly the deployed Agent's only model: callers may bind a separate
    # allow-list and default below.
    model_profile_id: str = Field(min_length=3, max_length=256)
    # Runtime is a Studio-owned deployment choice.  The authoring model only
    # supplies semantic intent and must not choose an incompatible framework
    # source contract on its own.
    runtime_type: Literal["codex", "adk", "langgraph"] = "codex"
    agent_model_profile_ids: list[str] = Field(default_factory=list, max_length=100)
    agent_default_model_profile_id: str | None = Field(
        default=None,
        min_length=3,
        max_length=256,
    )
    # Resource identities are selected by the Studio user, never generated by
    # the authoring model.  The API resolves and validates their contracts
    # before adding them to the returned Draft Patch.
    tool_resource_ids: list[str] = Field(default_factory=list, max_length=100)
    mcp_resource_ids: list[str] = Field(default_factory=list, max_length=100)
    skill_resource_ids: list[str] = Field(default_factory=list, max_length=100)
    # 可选的进度关联标识：前端生成后随请求带上，可通过
    # GET /api/v1/authoring/conversations:status/{request_id} 轮询构建阶段。
    request_id: str | None = Field(default=None, min_length=1, max_length=128)


class AuthoringCommitRequest(ContractModel):
    name: str | None = Field(default=None, min_length=1, max_length=128)
    slug: str | None = Field(default=None, min_length=1, max_length=63)
    model_profile_id: str | None = Field(default=None, min_length=3, max_length=256)


class ProjectInspectRequest(ContractModel):
    path: str = Field(min_length=1, max_length=4096)


class RunRequest(ContractModel):
    session_id: str | None = None
    model: str | None = Field(default=None, min_length=1, max_length=256)
    input: MessageInput
    environment: str = "local"
    stream: bool = True
    sandbox: str | None = None


class ConversationTurnRequest(ContractModel):
    """A capability-gated local Studio turn.

    Unlike the compatibility ``RunRequest`` this request deliberately contains
    only the provider-neutral ConversationInput. The server resolves the
    active Build's ConversationSurface and rejects undeclared intent before it
    reaches a framework-specific runtime request.
    """

    input: ConversationInput
    sandbox: str | None = None


class AgentScheduleRequest(ContractModel):
    """Browser-safe authoring input for one local ``ScheduledTask``.

    Stable Agent/Build/Kernel target fields are intentionally absent.  Studio
    resolves those from the active local Runtime binding and refuses creation
    when it cannot prove that binding.
    """

    display_name: str = Field(min_length=1, max_length=128)
    prompt: str = Field(min_length=1, max_length=32_768)
    schedule: ScheduleSpec
    enabled: bool = True
    continuity: Literal["new_session", "continue_session"] = "new_session"
    session_id: str | None = Field(default=None, min_length=1, max_length=256)


class InteractionSubmitRequest(ContractModel):
    name: str = Field(min_length=1, max_length=64)
    data: dict[str, Any] = Field(default_factory=dict)
    expected_revision: int = Field(alias="expectedRevision", ge=1)
    idempotency_key: str = Field(alias="idempotencyKey", min_length=1, max_length=256)


class CloudChatMessageRequest(ContractModel):
    """One cloud turn submitted through Studio's loopback control plane.

    The loopback process, never the browser, owns the AK/SK used to admit the
    message through the cloud control plane.  ``content`` uses the same
    OpenAI-compatible text/image/file part shape as RunAgent; execution-policy
    fields remain bounded enums and are revalidated by Server/Runtime.
    """

    content: str | list[dict[str, Any]]
    model: str | None = Field(default=None, min_length=1, max_length=256)
    model_options: dict[str, Any] = Field(default_factory=dict)
    tool_approval_mode: Literal["ask", "risk", "full"] = "risk"
    collaboration_mode: Literal["default", "plan"] | None = None
    goal_objective: str | None = Field(default=None, min_length=1, max_length=4096)

    @field_validator("content")
    @classmethod
    def validate_content(cls, value):
        if isinstance(value, str):
            if not value.strip():
                raise ValueError("content must not be empty")
            if len(value) > 1_000_000:
                raise ValueError("text content is too large")
            return value
        if not 1 <= len(value) <= 9:
            raise ValueError("content must contain between 1 and 9 parts")
        attachment_count = 0
        for part in value:
            kind = str(part.get("type") or "")
            if kind == "input_text":
                text = part.get("text")
                if not isinstance(text, str) or not text.strip() or len(text) > 1_000_000:
                    raise ValueError("input_text must contain bounded non-empty text")
                continue
            if kind == "input_image":
                attachment_count += 1
                url = part.get("image_url")
                if not isinstance(url, str) or not url or len(url) > 14_000_000:
                    raise ValueError("input_image must contain a bounded image_url")
                continue
            if kind == "input_file":
                attachment_count += 1
                filename = part.get("filename")
                data = part.get("file_data") or part.get("file_url")
                if not isinstance(filename, str) or not filename.strip():
                    raise ValueError("input_file must contain a filename")
                if not isinstance(data, str) or not data or len(data) > 14_000_000:
                    raise ValueError("input_file must contain bounded file data")
                continue
            raise ValueError(f"unsupported content part: {kind or '<missing>'}")
        if attachment_count > 8:
            raise ValueError("a turn supports at most 8 attachments")
        return value


class CloudChatInteractionSubmitRequest(ContractModel):
    """Public Interaction/v1 fields accepted by the local cloud-chat proxy."""

    run_id: str = Field(min_length=1, max_length=256)
    interaction_id: str = Field(min_length=1, max_length=256)
    expected_revision: int = Field(ge=1)
    action: Literal["approve", "reject", "submit", "cancel"]
    response: dict[str, Any] = Field(default_factory=dict)
    idempotency_key: str = Field(min_length=1, max_length=256)


class StudioEvaluationCreate(ContractModel):
    """Request for the shared CLI/Studio evaluation executor."""

    evalset_file: str = Field(min_length=1, max_length=4096)
    target: TargetRef
    config: PublicEvaluationConfig = Field(default_factory=PublicEvaluationConfig)


class SecretReferenceCheckRequest(ContractModel):
    ref: str


class CredentialPutRequest(ContractModel):
    value: SecretStr = Field(min_length=1, max_length=16_384)
    persistence: Literal["session"] = "session"


class RollbackRequest(ContractModel):
    target_build_id: str


class CloudAgentVersionRollbackRequest(ContractModel):
    version_id: str = Field(min_length=1, max_length=256)


class ModelProfileCreateRequest(ContractModel):
    name: str = Field(pattern=r"^[a-z][a-z0-9._-]{1,127}$")
    display_name: str = Field(min_length=1, max_length=128)
    version: str = Field(default="1.0.0", min_length=1, max_length=64)
    description: str = Field(default="", max_length=4096)
    spec: ModelSpec


class ModelEndpointProbeRequest(ContractModel):
    url: str = Field(min_length=8, max_length=1024)
    credential_ref: str | None = Field(default=None, max_length=512)
    api_key: SecretStr | None = None


class MCPResourceCreateRequest(ContractModel):
    display_name: str = Field(min_length=1, max_length=128)
    description: str = Field(default="", max_length=4096)
    server: MCPServerRef


class ToolResourceCreateRequest(ContractModel):
    display_name: str = Field(min_length=1, max_length=128)
    category: str = Field(default="custom", max_length=64)
    contract: ToolContract


class PythonToolCommitRequest(ContractModel):
    display_name: str = Field(min_length=1, max_length=128)
    name: str = Field(pattern=r"^[A-Za-z_][A-Za-z0-9_]{0,127}$")
    callable_name: str = Field(pattern=r"^[A-Za-z_][A-Za-z0-9_]{0,127}$")
    description: str = Field(default="", max_length=1024)


class ToolSchemaValidationRequest(ContractModel):
    schema_definition: dict[str, Any] = Field(alias="schema")
    sample: Any = None


class ToolPolicyPreviewRequest(ContractModel):
    bindings: AgentBindings


class SkillDiscoveryRequest(ContractModel):
    scan_paths: list[str] = Field(default_factory=list, max_length=20)


class SkillDiscoveryCommitRequest(ContractModel):
    candidate_id: str = Field(min_length=1, max_length=128)
    overwrite: bool = False


__all__ = [name for name in globals() if name.endswith("Request")]
