from __future__ import annotations

import asyncio
import sys
import types
from typing import Any

from ksadk.conversations import runtime_compaction as _runtime_compaction
from ksadk.conversations import runtime_governance as _runtime_governance
from ksadk.conversations import runtime_input as _runtime_input
from ksadk.conversations import runtime_invocation as _runtime_invocation
from ksadk.conversations import runtime_metadata as _runtime_metadata
from ksadk.conversations import runtime_observability as _runtime_observability
from ksadk.conversations import runtime_payloads as _runtime_payloads
from ksadk.conversations import runtime_persistence as _runtime_persistence
from ksadk.conversations import runtime_preparation as _runtime_preparation
from ksadk.conversations import runtime_resume as _runtime_resume
from ksadk.conversations import runtime_stream_events as _runtime_stream_events
from ksadk.conversations import runtime_streaming as _runtime_streaming
from ksadk.conversations.runtime_compaction import (
    _plan_compaction,
    compact_conversation_history,
    preview_auto_compaction,
)
from ksadk.conversations.runtime_constants import (
    _MODEL_CATALOG_CACHE,
    _MODEL_CATALOG_CACHE_TTL_SECONDS,
    ATTACHMENT_CONTEXT_STATE_KEY,
    AUTOCOMPACT_KEEP_TAIL_GROUPS,
    EVENT_SCAN_PAGE_SIZE,
    PROMPT_TOO_LONG_MARKERS,
    PTL_RETRY_KEEP_TAIL_GROUPS,
    SESSION_SUMMARY_MAX_CHARS,
)
from ksadk.conversations.runtime_governance import (
    RuntimeCircuitOpen,
    RuntimeGovernanceState,
    _compact_conversation_history_with_governance,
    _governance_error,
    _governance_record_approval_response,
    _governance_record_compact_failure,
    _governance_record_compact_success,
    _governance_record_tool_call,
    _governance_record_tool_result,
    _governance_record_turn_start,
    _int_env,
    _runtime_governance_from_env,
    _tool_observability_metadata,
)
from ksadk.conversations.runtime_input import (
    _ambient_context_has_error,
    _ambient_policy,
    _attachment_summary_for_memory,
    _auto_save_ltm_turn,
    _build_runner_ambient_contexts,
    _build_runner_request_payload,
    _contains_any_fragment,
    _env_flag,
    _inject_runner_deferred_tools_for_request,
    _input_text_for_memory,
    _is_chitchat_query,
    _is_prompt_too_long_error,
    _ltm_auto_save_enabled,
    _memory_turn_event_strings,
    _merge_request_history_with_session_history,
    _merge_responses_history_with_session_history,
    _normalize_ambient_query,
    _runner_name,
    _runner_type_name,
    _should_load_kb_ambient_context,
    _should_load_memory_ambient_context,
    _should_use_platform_ambient_context,
)
from ksadk.conversations.runtime_invocation import (
    _response_sse,
    invoke_conversation_once,
)
from ksadk.conversations.runtime_metadata import (
    _attachment_context_from_session,
    _build_attachment_context_state_delta,
    _build_pending_user_event,
    _canonical_input_messages,
    _fetch_remote_model_catalog,
    _latest_attachment_context_from_messages,
    _latest_user_turn,
    _model_catalog_endpoint,
    _normalized_conversation_messages,
    _parts_include_file,
    _refine_session_title_in_background,
    _resolve_effective_attachment_context,
    _resolve_model_metadata,
    _resolve_runtime_model_metadata,
    _transcript_event_type,
    _truncate_text,
    _update_session_metadata_after_assistant_turn,
    _update_session_metadata_after_user_turn,
    _user_event_content,
    prime_session_metadata_for_user_turn,
)
from ksadk.conversations.runtime_observability import (
    _chat_usage_payload,
    _conversation_span_scope,
    _current_span_feedback_metadata,
    _extract_deferred_tool_names,
    _get_conversation_tracer,
    _get_current_span,
    _latest_deferred_tool_names,
    _normalize_usage_payload,
    _responses_usage_payload,
    _set_conversation_input_attributes,
    _set_conversation_output_attributes,
    _set_conversation_span_attributes,
    _set_conversation_usage_attributes,
    _set_span_attribute,
    _span_current_context,
    _span_feedback_metadata,
    _usage_from_metadata,
)
from ksadk.conversations.runtime_payloads import (
    CompactionPlan,
    PreparedConversationTurn,
    build_chat_completions_payload,
    build_compaction_sse_event,
    build_responses_payload,
    extract_responses_resume_input,
)
from ksadk.conversations.runtime_persistence import (
    _find_latest_session_event,
    append_context_checkpoint_event,
    append_conversation_event,
    append_deferred_tools_event,
    append_reasoning_event,
    append_run_checkpoint_event,
    append_run_resume_event,
    append_run_status_event,
    ensure_conversation_session,
)
from ksadk.conversations.runtime_preparation import (
    _refresh_history,
    build_run_input,
)
from ksadk.conversations.runtime_resume import (
    _agentengine_resume_metadata,
    _approval_decision_from_resume,
    _approval_request_events,
    _approval_request_id_from_event,
    _approval_resume_run_mode,
    _builtin_tool_callable,
    _checkpoint_event_args_from_agentengine_metadata,
    _consecutive_approval_denials_from_events,
    _execute_approved_builtin_tool_resume,
    _extract_agentengine_metadata,
    _failed_status_for_resume,
    _filter_responses_reasoning_output,
    _find_tool_receipt_event_by_key,
    _format_resume_response_text,
    _has_pending_approval,
    _is_approval_resume_input,
    _is_checkpoint_resume_input,
    _latest_checkpoint_metadata_for_run,
    _merge_agentengine_metadata,
    _model_options_disable_reasoning,
    _normalize_approval_resume_input,
    _normalize_checkpoint_resume_input,
    _parse_approval_arguments,
    _pending_approval_events,
    _responses_output_item_text,
    _semantic_events_from_responses_output,
    _stringify_responses_item_value,
    _tool_receipt_idempotency_key_for_resume,
    _tool_receipt_metadata,
    _tool_receipt_status_from_output,
    _tool_resume_run_id,
)
from ksadk.conversations.runtime_stream_events import (
    _iter_conversation_turn_events,
)
from ksadk.conversations.runtime_streaming import (
    stream_conversation_turn,
    stream_responses_conversation_turn,
)
from ksadk.conversations.session_title import (
    resolve_session_title_client,
)
from ksadk.knowledge_base.service import KnowledgeBaseService
from ksadk.memory.service import LongTermMemoryService
from ksadk.sessions import resolve_session_service

_FACADE_EXPORTS = (
    ATTACHMENT_CONTEXT_STATE_KEY,
    AUTOCOMPACT_KEEP_TAIL_GROUPS,
    CompactionPlan,
    EVENT_SCAN_PAGE_SIZE,
    KnowledgeBaseService,
    LongTermMemoryService,
    PROMPT_TOO_LONG_MARKERS,
    PTL_RETRY_KEEP_TAIL_GROUPS,
    PreparedConversationTurn,
    RuntimeCircuitOpen,
    RuntimeGovernanceState,
    SESSION_SUMMARY_MAX_CHARS,
    _MODEL_CATALOG_CACHE,
    _MODEL_CATALOG_CACHE_TTL_SECONDS,
    _agentengine_resume_metadata,
    _ambient_context_has_error,
    _ambient_policy,
    _approval_decision_from_resume,
    _approval_request_events,
    _approval_request_id_from_event,
    _approval_resume_run_mode,
    _attachment_context_from_session,
    _attachment_summary_for_memory,
    _auto_save_ltm_turn,
    _build_attachment_context_state_delta,
    _build_pending_user_event,
    _build_runner_ambient_contexts,
    _build_runner_request_payload,
    _builtin_tool_callable,
    _canonical_input_messages,
    _chat_usage_payload,
    _checkpoint_event_args_from_agentengine_metadata,
    _compact_conversation_history_with_governance,
    _consecutive_approval_denials_from_events,
    _contains_any_fragment,
    _conversation_span_scope,
    _current_span_feedback_metadata,
    _env_flag,
    _execute_approved_builtin_tool_resume,
    _extract_agentengine_metadata,
    _extract_deferred_tool_names,
    _failed_status_for_resume,
    _fetch_remote_model_catalog,
    _filter_responses_reasoning_output,
    _find_latest_session_event,
    _find_tool_receipt_event_by_key,
    _format_resume_response_text,
    _get_conversation_tracer,
    _get_current_span,
    _governance_error,
    _governance_record_approval_response,
    _governance_record_compact_failure,
    _governance_record_compact_success,
    _governance_record_tool_call,
    _governance_record_tool_result,
    _governance_record_turn_start,
    _has_pending_approval,
    _inject_runner_deferred_tools_for_request,
    _input_text_for_memory,
    _int_env,
    _is_approval_resume_input,
    _is_checkpoint_resume_input,
    _is_chitchat_query,
    _is_prompt_too_long_error,
    _iter_conversation_turn_events,
    _latest_attachment_context_from_messages,
    _latest_checkpoint_metadata_for_run,
    _latest_deferred_tool_names,
    _latest_user_turn,
    _ltm_auto_save_enabled,
    _memory_turn_event_strings,
    _merge_agentengine_metadata,
    _merge_request_history_with_session_history,
    _merge_responses_history_with_session_history,
    _model_catalog_endpoint,
    _model_options_disable_reasoning,
    _normalize_ambient_query,
    _normalize_approval_resume_input,
    _normalize_checkpoint_resume_input,
    _normalize_usage_payload,
    _normalized_conversation_messages,
    _parse_approval_arguments,
    _parts_include_file,
    _pending_approval_events,
    _plan_compaction,
    _refine_session_title_in_background,
    _refresh_history,
    _resolve_effective_attachment_context,
    _resolve_model_metadata,
    _resolve_runtime_model_metadata,
    _response_sse,
    _responses_output_item_text,
    _responses_usage_payload,
    _runner_name,
    _runner_type_name,
    _runtime_governance_from_env,
    _semantic_events_from_responses_output,
    _set_conversation_input_attributes,
    _set_conversation_output_attributes,
    _set_conversation_span_attributes,
    _set_conversation_usage_attributes,
    _set_span_attribute,
    _should_load_kb_ambient_context,
    _should_load_memory_ambient_context,
    _should_use_platform_ambient_context,
    _span_current_context,
    _span_feedback_metadata,
    _stringify_responses_item_value,
    _tool_observability_metadata,
    _tool_receipt_idempotency_key_for_resume,
    _tool_receipt_metadata,
    _tool_receipt_status_from_output,
    _tool_resume_run_id,
    _transcript_event_type,
    _truncate_text,
    _update_session_metadata_after_assistant_turn,
    _update_session_metadata_after_user_turn,
    _usage_from_metadata,
    _user_event_content,
    append_context_checkpoint_event,
    append_conversation_event,
    append_deferred_tools_event,
    append_reasoning_event,
    append_run_checkpoint_event,
    append_run_resume_event,
    append_run_status_event,
    asyncio,
    build_chat_completions_payload,
    build_compaction_sse_event,
    build_responses_payload,
    build_run_input,
    compact_conversation_history,
    ensure_conversation_session,
    extract_responses_resume_input,
    invoke_conversation_once,
    preview_auto_compaction,
    prime_session_metadata_for_user_turn,
    resolve_session_service,
    resolve_session_title_client,
    stream_conversation_turn,
    stream_responses_conversation_turn,
)


_IMPL_MODULES = (
    _runtime_compaction,
    _runtime_governance,
    _runtime_observability,
    _runtime_payloads,
    _runtime_input,
    _runtime_resume,
    _runtime_metadata,
    _runtime_persistence,
    _runtime_preparation,
    _runtime_invocation,
    _runtime_stream_events,
    _runtime_streaming,
)


class _RuntimeFacadeModule(types.ModuleType):
    """Keep historical runtime-module monkeypatches visible to moved implementations."""

    def __setattr__(self, name: str, value: Any) -> None:
        super().__setattr__(name, value)
        for module in _IMPL_MODULES:
            if name in module.__dict__:
                setattr(module, name, value)


sys.modules[__name__].__class__ = _RuntimeFacadeModule
